import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "./lib/utils";
import Navbar from "../components/Navbar";
import { useContext } from "react";
import { GlobalContextProvider } from "./Context/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sass",
  description: "Generated by Rudra",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className="light">
      <body className={cn(
        "min-h-screen font-sans antialiased grainy",
        inter.className
      )}>
        <GlobalContextProvider>
        <Navbar/>
        {children}
        </GlobalContextProvider>
        </body>
    </html>
  );
}

